# Generated by Django 4.2.5 on 2023-10-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_remove_book_department_book_sub_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sub_department',
        ),
        migrations.AddField(
            model_name='book',
            name='sub_departments',
            field=models.ManyToManyField(blank=True, to='book.subdepartment'),
        ),
    ]
