# Generated by Django 4.2.5 on 2023-10-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_remove_book_sub_department_book_sub_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sub_departments',
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='booklist',
            field=models.ManyToManyField(related_name='sub_departments', to='book.book'),
        ),
    ]
