# Generated by Django 4.2.5 on 2023-10-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_remove_book_sub_departments_subdepartment_booklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='booklist',
            field=models.ManyToManyField(related_name='booklist', to='book.book'),
        ),
    ]
