# Generated by Django 4.2.5 on 2023-10-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_subdepartment_booklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='subdepartment_id',
            field=models.IntegerField(default=0),
        ),
    ]
