# Generated by Django 4.2.5 on 2023-10-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_subdepartment_booklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdepartment',
            name='subdepartment_id',
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='booklist',
            field=models.ManyToManyField(blank=True, related_name='booklist', to='book.book'),
        ),
    ]
