# Generated by Django 4.2.5 on 2023-10-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_remove_subdepartment_subdepartment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.department'),
        ),
    ]
